### ISSUE TITLE
`bisync/Cargo.toml` is missing `repository` entry

### ISSUE THREAD

**Issue by Marcono1234** [JM4ier/bisync#1]
Hello,
the `bisync/Cargo.toml` file is currently missing a `repository` entry; this makes it a bit difficult to find this repository here.

(`bisync_macros/Cargo.toml` has a `repository` entry)

**Comment by JM4ier** [comment]
fixed with release 0.2.3 (4ecaf2aa3ec78b299155f73865586f79aaa3c30d)

**Comment by Marcono1234** [comment]
Thanks!
