### ISSUE TITLE
`bisync_macros` has no README

### ISSUE THREAD

**Issue by Marcono1234** [JM4ier/bisync#2]
`bisync_macros` has no README. When someone stumbles upon it on crates.io it might not be obvious what it is used for.

Not sure if it makes sense to duplicate the main README. Maybe instead a minimal README which mentions that the macros are used by `bisync` (with a link to it) would be useful. What do you think?

**Comment by JM4ier** [comment]
fixed with release 0.2.3 (4ecaf2aa3ec78b299155f73865586f79aaa3c30d)
